name: CI/CD Pipeline
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup and run tests for server
        working-directory: ./server
        run: |
          pnpm install
          pnpm lint
          pnpm typecheck
          pnpm test
